### ISSUE TITLE
How to download the videos from RealEstate10k

### ISSUE THREAD

**Issue by Yuancheng-Xu** [hehao13/CameraCtrl#20]
The official [RealEstate10k](https://google.github.io/realestate10k/download.html) only provides YouTube link to the videos, and there are a lot of them. I am wondering if there are available scripts to download these videos in a scalable and robust way. Thank you!

**Comment by jsxzs** [comment]
@Yuancheng-Xu Did you solve the issue? If yes, could you please share your method to download these videos. Thank you!
